const BASE="https://developer.zhihu.com";
const HACKATHON_BASE="https://api.zhihu.com/km-indep-home/hackathon/v2";
const DEFAULT_REQUEST_INTERVAL_MS=1200;
export class AppError extends Error{constructor(code,message,status=502){super(message);this.code=code;this.status=status}}
const clean=(value,max=10000)=>String(value??"").replace(/<\/?em>/gi,"").replace(/\s+/g," ").trim().slice(0,max);
export function safeZhihuUrl(value){try{const url=new URL(value);return url.protocol==="https:"&&["www.zhihu.com","zhuanlan.zhihu.com"].includes(url.hostname)}catch{return false}}
export function normalizeItem(item){if(!safeZhihuUrl(item?.Url))return null;return{id:clean(item.ContentID,200),type:clean(item.ContentType,30).toLowerCase(),title:clean(item.Title,300),excerpt:clean(item.ContentText),url:item.Url,author:clean(item.AuthorName,120)||"知乎用户",avatar:String(item.AuthorAvatar??""),votes:Math.max(0,Number(item.VoteUpCount??0)),comments:Math.max(0,Number(item.CommentCount??0)),authority:clean(item.AuthorityLevel,10),editedAt:Number(item.EditTime??0)}}
export function parseStructuredModelOutput(text){text=String(text??"").replace(/^```(?:json)?\s*/i,"").replace(/\s*```$/i,"").trim();try{return JSON.parse(text)}catch{}let start=-1,depth=0,quoted=false,escaped=false;for(let index=0;index<text.length;index++){const char=text[index];if(quoted){if(escaped)escaped=false;else if(char==="\\")escaped=true;else if(char==='"')quoted=false;continue}if(char==='"'){quoted=true;continue}if(char==="{"){if(depth===0)start=index;depth++}else if(char==="}"&&depth>0){depth--;if(depth===0){try{return JSON.parse(text.slice(start,index+1))}catch{start=-1}}}}return null}
const demo=query=>({demo:true,items:[{id:"demo-001",type:"answer",title:`关于“${query}”的示例回答`,excerpt:"当前未配置服务端 Access Secret，这是用于验证人工归档、来源跳转和 AI 审批闭环的演示内容。上线配置后将显示知乎开放平台真实结果。",url:"https://www.zhihu.com/",author:"演示数据",avatar:"",votes:128,comments:16,authority:"2",editedAt:0}]});
const searchTokens=query=>{const text=clean(query,200).toLowerCase().replace(/\s+/g,"");const tokens=new Set(text.match(/[a-z0-9]+/g)??[]);for(let index=0;index<text.length-1;index++)tokens.add(text.slice(index,index+2));return [...tokens].filter(Boolean)};
const publicSearchScore=(item,tokens)=>{const title=String(item.title??"").toLowerCase(),body=`${title} ${item.description??""} ${(item.labels??[]).join(" ")}`.toLowerCase();return tokens.reduce((score,token)=>score+(title.includes(token)?5:body.includes(token)?1:0),0)};
export class ZhihuClient{
 constructor({accessSecret,fetchImpl=fetch,requestIntervalMs=DEFAULT_REQUEST_INTERVAL_MS}={}){this.secret=accessSecret?.trim();this.fetch=fetchImpl;this.configured=Boolean(this.secret);this.cache=new Map();this.requestIntervalMs=Math.max(0,Number(requestIntervalMs)||0);this.nextRequestAt=0;this.requestGate=Promise.resolve();this.searchFallbackUntil=0}
 async waitForRequestTurn(){const previous=this.requestGate;let release;this.requestGate=new Promise(resolve=>{release=resolve});await previous;const wait=Math.max(0,this.nextRequestAt-Date.now());if(wait)await new Promise(resolve=>setTimeout(resolve,wait));this.nextRequestAt=Date.now()+this.requestIntervalMs;release()}
 async request(path,{method="GET",body,oauthToken}={}){if(!this.secret)throw new AppError("ZHIHU_NOT_CONFIGURED","尚未配置知乎 Access Secret。",503);await this.waitForRequestTurn();let response;try{response=await this.fetch(`${BASE}${path}`,{method,redirect:"error",signal:AbortSignal.timeout(30000),headers:{Authorization:`Bearer ${this.secret}`,"X-Request-Timestamp":String(Math.floor(Date.now()/1000)),"Content-Type":"application/json",...(oauthToken?{"X-OAuth-Token":oauthToken}:{})},body:body?JSON.stringify(body):undefined})}catch{throw new AppError("ZHIHU_UNAVAILABLE","无法连接知乎开放平台。")}const text=await response.text();if(text.length>2000000)throw new AppError("ZHIHU_RESPONSE_INVALID","知乎返回内容超过安全上限。");let payload;try{payload=JSON.parse(text)}catch{throw new AppError("ZHIHU_RESPONSE_INVALID","知乎返回内容无法解析。")}if(!response.ok||(payload.Code!==undefined&&payload.Code!==0)){const code=Number(payload.Code??response.status);if(code===20001||[401,403].includes(response.status))throw new AppError("ZHIHU_AUTH_FAILED","知乎接口鉴权失败。",502);if([30001,30002].includes(code)||response.status===429)throw new AppError("ZHIHU_QUOTA_EXHAUSTED","知乎接口额度或频率已受限，请稍后重试。",429);throw new AppError("ZHIHU_UNAVAILABLE","知乎接口暂时不可用。")}return payload}
 cached(key,fn){const hit=this.cache.get(key);if(hit&&hit.until>Date.now())return hit.value;const value=Promise.resolve().then(fn);this.cache.set(key,{until:Date.now()+300000,value});value.catch(()=>this.cache.delete(key));return value}
 async publicSearch(query,count,reason="missing-secret"){return this.cached(`public-search:${query}:${count}`,async()=>{try{const [knowledge,stories]=await Promise.all([this.hackathonContent("knowledge"),this.hackathonContent("story")]),tokens=searchTokens(query),ranked=[...knowledge.items,...stories.items].map(item=>({item,score:publicSearchScore(item,tokens)})).filter(entry=>entry.score>0).sort((left,right)=>right.score-left.score||left.item.title.localeCompare(right.item.title,"zh-CN")).slice(0,count);return{demo:false,limited:true,source:"zhihu-hackathon",fallbackReason:reason,items:ranked.map(({item})=>({id:item.workId,type:"赛事内容",title:item.title,excerpt:item.description,url:"",author:"知乎创作者",avatar:item.artwork,votes:0,comments:0,authority:"",editedAt:0}))}}catch{return demo(query)}})}
 async search(query,count=8){query=clean(query,200);if(!query)throw new AppError("VALIDATION_FAILED","请输入搜索关键词。",400);count=Math.min(10,Math.max(1,Math.floor(Number(count)||8)));if(!this.configured)return this.publicSearch(query,count);if(this.searchFallbackUntil>Date.now())return this.publicSearch(query,count,"quota");try{return await this.cached(`s:${query}:${count}`,async()=>{const payload=await this.request(`/api/v1/content/zhihu_search?Query=${encodeURIComponent(query)}&Count=${count}`);return{demo:false,limited:false,source:"zhihu-search",emptyReason:clean(payload.Data?.EmptyReason,300),items:(payload.Data?.Items??[]).map(normalizeItem).filter(Boolean)}})}catch(error){if(error?.code!=="ZHIHU_QUOTA_EXHAUSTED")throw error;this.searchFallbackUntil=Date.now()+5*60*1000;return this.publicSearch(query,count,"quota")}}
 async hot(limit=10){limit=Math.min(30,Math.max(1,Math.floor(Number(limit)||10)));if(!this.configured)return demo("校园学习与职业成长");return this.cached(`h:${limit}`,async()=>{const payload=await this.request(`/api/v1/content/hot_list?Limit=${limit}`);return{demo:false,items:(payload.Data?.Items??[]).filter(item=>safeZhihuUrl(item.Url)).map((item,index)=>({id:`hot-${index}`,type:"hot",title:clean(item.Title,300),excerpt:clean(item.Summary),url:item.Url,author:"知乎热榜",avatar:item.ThumbnailUrl??"",votes:0,comments:0,authority:"",editedAt:0}))}})}
 async quota(){if(!this.configured)return{configured:false,items:[]};const payload=await this.request("/api/v1/quota?APIIDs=zhihu_search,hot_list,zhida_openai");return{configured:true,items:payload.Data??[]}}
 async hackathonContent(type){if(!new Set(["story","knowledge"]).has(type))throw new AppError("VALIDATION_FAILED","不支持的活动内容类型。",400);return this.cached(`hackathon:${type}`,async()=>{let response;try{response=await this.fetch(`${HACKATHON_BASE}/${type}/list`,{headers:{Accept:"application/json"},redirect:"error",signal:AbortSignal.timeout(15000)})}catch{throw new AppError("ZHIHU_UNAVAILABLE","无法连接知乎黑客松内容接口。")}if(!response.ok)throw new AppError("ZHIHU_UNAVAILABLE","知乎黑客松内容接口暂时不可用。");let payload;try{payload=await response.json()}catch{throw new AppError("ZHIHU_RESPONSE_INVALID","知乎黑客松内容返回无法解析。")}if(!Array.isArray(payload))throw new AppError("ZHIHU_RESPONSE_INVALID","知乎黑客松内容结构无效。");return{activity:"zhihu_hackathon_2026_p2",type,items:payload.slice(0,100).map(item=>({workId:clean(item?.work_id,100),title:clean(item?.title,300),description:clean(item?.description,3000),artwork:String(item?.artwork??""),tabArtwork:String(item?.tab_artwork??""),labels:Array.isArray(item?.labels)?item.labels.slice(0,20).map(label=>clean(label,40)):[]})).filter(item=>item.workId&&item.title)}})}
 async userContents(oauthToken,limit=20,offset="0"){if(!oauthToken)throw new AppError("AUTH_REQUIRED","请先使用知乎账号登录。",401);limit=Math.min(50,Math.max(1,Math.floor(Number(limit)||20)));offset=clean(offset,200)||"0";const payload=await this.request(`/api/v1/user/contents?ContentType=all&SortField=ts&SortOrder=desc&Offset=${encodeURIComponent(offset)}&Limit=${limit}`,{oauthToken});return{items:(payload.Data?.Items??[]).map(item=>({type:clean(item.ContentType,30),title:clean(item.Title,300),summary:clean(item.Summary,5000),url:safeZhihuUrl(item.Url)?item.Url:"",createdAt:Number(item.CreatedAt??0),likeCount:Math.max(0,Number(item.LikeCount??0)),commentCount:Math.max(0,Number(item.CommentCount??0)),favoriteCount:Math.max(0,Number(item.FavoriteCount??0))})),paging:payload.Data?.Paging??{IsEnd:true}}}
 async userFollowees(oauthToken,limit=20,offset="0"){if(!oauthToken)throw new AppError("AUTH_REQUIRED","请先使用知乎账号登录。",401);limit=Math.min(50,Math.max(1,Math.floor(Number(limit)||20)));offset=clean(offset,200)||"0";const payload=await this.request(`/api/v1/user/followees?Offset=${encodeURIComponent(offset)}&Limit=${limit}`,{oauthToken});return{items:(payload.Data?.Items??[]).map(item=>{const token=clean(item.UrlToken??item.UserToken??item.url_token,200),rawUrl=item.Url??(token?`https://www.zhihu.com/people/${encodeURIComponent(token)}`:"");return{uid:clean(item.Uid??item.UID??item.Id??item.ID,200),name:clean(item.Name??item.Fullname??item.UserName,120)||"知乎用户",headline:clean(item.Headline??item.Description,500),avatar:String(item.AvatarUrl??item.AvatarPath??item.Avatar??""),url:safeZhihuUrl(rawUrl)?rawUrl:"",followerCount:Math.max(0,Number(item.FollowerCount??item.FollowersCount??0))}}),paging:payload.Data?.Paging??{IsEnd:true}}}
 async assist(input){
  const allowed=new Set(["connect","integrate","summarize-node","summarize-edge","summarize-network"]),task=allowed.has(input?.task)?input.task:null,rawNodes=Array.isArray(input?.nodes)?input.nodes:[];
  if(rawNodes.length>120)throw new AppError("VALIDATION_FAILED","单次最多处理 120 个节点。",400);
  const nodes=rawNodes.map(node=>({id:clean(node.id,100),title:clean(node.title,300),note:clean(node.note,10000),excerpt:clean(node.excerpt,2000)})),edges=(Array.isArray(input?.existingEdges)?input.existingEdges:[]).slice(0,240).map(edge=>({id:clean(edge.id,100),sourceNodeId:clean(edge.sourceNodeId,100),targetNodeId:clean(edge.targetNodeId,100),title:clean(edge.title,200),note:clean(edge.rationale??edge.note,2000),relationType:clean(edge.relationType,40)})),nodeIds=new Set(nodes.map(node=>node.id)),candidateNodeIds=new Set((Array.isArray(input?.candidateNodeIds)?input.candidateNodeIds:[]).map(id=>clean(id,100)).filter(id=>nodeIds.has(id)));
  if(!task||!nodes.length)throw new AppError("VALIDATION_FAILED","AI 任务或节点无效。",400);if(task==="integrate"&&!candidateNodeIds.size)throw new AppError("VALIDATION_FAILED","请选择需要整合的新增节点。",400);
  if(!this.configured)return this.demoAssist(task,nodes,edges,input.edgeId,candidateNodeIds);
  const edgeRule='只输出JSON：{"edges":[{"sourceNodeId":"","targetNodeId":"","title":"","note":"","relationType":"related","confidence":0.8,"rationale":""}]}。ID只能来自节点目录；不得创建节点、自环、重复现有关系或编造事实；关系文字必须直接使用真实概念名，不得写“节点1”等机械代称。',rules={connect:edgeRule,integrate:`${edgeRule} 每条建议关系至少一端必须属于待整合节点；对每个待整合节点通常给出 3～5 条可靠关系，缺乏相关性时宁可少给或不给。`,"summarize-node":'只输出JSON：{"note":"Markdown总结","impactSummary":"将更新节点说明"}。只能依据给定节点及来源摘录。',"summarize-edge":'只输出JSON：{"note":"Markdown总结","impactSummary":"将更新关系说明"}。总结指定关系的两端节点、关系语义和证据，不得补造事实。',"summarize-network":'只输出JSON：{"note":"Markdown总结","impactSummary":"将更新网络说明"}。只能依据当前网络目录，说明主题、关键簇与尚未连接部分。'};
  const payload=await this.request("/v1/chat/completions",{method:"POST",body:{model:task==="summarize-network"?"zhida-thinking-1p5":"zhida-fast-1p5",messages:[{role:"system",content:rules[task]},{role:"user",content:JSON.stringify({nodes,existingEdges:edges,targetEdgeId:input.edgeId??null,candidateNodeIds:[...candidateNodeIds]})}],stream:false}}),result=parseStructuredModelOutput(payload.choices?.[0]?.message?.content);
  if(!result)throw new AppError("ZHIHU_RESPONSE_INVALID","知乎直答未返回有效结构化结果。");return{demo:false,result:this.validateAssist(task,nodes,result,{edges,edgeId:input.edgeId,candidateNodeIds})}
 }
 validateAssist(task,nodes,result,{edges=[],edgeId,candidateNodeIds=new Set()}={}){if(!result||typeof result!=="object"||Array.isArray(result))throw new AppError("ZHIHU_RESPONSE_INVALID","AI 草案结构无效。");if(task!=="connect"&&task!=="integrate"){const note=clean(result.note,10000);if(!note)throw new AppError("ZHIHU_RESPONSE_INVALID","AI 总结为空。");return{note,impactSummary:clean(result.impactSummary,300),...(task==="summarize-edge"?{edgeId:clean(edgeId,100)}:{})}}const ids=new Set(nodes.map(node=>node.id)),pairs=new Set(edges.map(edge=>[edge.sourceNodeId,edge.targetNodeId].sort().join(":"))),allowed=new Set(["supports","supplements","contradicts","condition_of","example_of","related"]),output=[];for(const edge of Array.isArray(result.edges)?result.edges.slice(0,60):[]){const source=clean(edge.sourceNodeId,100),target=clean(edge.targetNodeId,100),pair=[source,target].sort().join(":");if(!ids.has(source)||!ids.has(target)||source===target||pairs.has(pair)||(task==="integrate"&&!candidateNodeIds.has(source)&&!candidateNodeIds.has(target)))continue;pairs.add(pair);output.push({sourceNodeId:source,targetNodeId:target,title:clean(edge.title,120)||"相关",note:clean(edge.note,1000),relationType:allowed.has(edge.relationType)?edge.relationType:"related",confidence:Math.min(1,Math.max(0,Number(edge.confidence)||0)),rationale:clean(edge.rationale,2000)||"请根据来源人工核对。"})}return{edges:output}}
 demoAssist(task,nodes,edges,edgeId,candidateNodeIds=new Set()){if(task==="connect"||task==="integrate"){if(nodes.length<2)throw new AppError("VALIDATION_FAILED","请选择至少两个节点。",400);const candidate=task==="integrate"?nodes.find(node=>candidateNodeIds.has(node.id)):nodes[0],target=nodes.find(node=>node.id!==candidate?.id);return{demo:true,result:this.validateAssist(task,nodes,{edges:candidate&&target?[{sourceNodeId:candidate.id,targetNodeId:target.id,title:"相互补充",note:"两个节点从不同来源补充同一主题。",relationType:"supplements",confidence:.72,rationale:"演示建议，请根据原文人工核对。"}]:[]},{edges,candidateNodeIds})}}const note=task==="summarize-edge"?`**关系总结**：${edges.find(edge=>edge.id===edgeId)?.title||"所选关系"}连接了两个由用户归档的知识节点，请结合原文核对。`:nodes.map(node=>`- **${node.title}**：${node.note||node.excerpt||"尚未填写说明"}`).join("\n");return{demo:true,result:{note:task==="summarize-network"?`该网络围绕以下人工归档节点展开：\n${note}`:note.replace(/^- /,""),impactSummary:task==="summarize-edge"?"将更新关系说明":task==="summarize-node"?"将更新节点说明":"将更新网络说明",...(task==="summarize-edge"?{edgeId}:{})}}}
}
